---
# tasks file for roles/myfirewall
# >>> 변수 - fw_80, fw_433 <<<
- name: 패키지 설치 -firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: 서비스 기동 - firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: 포트 등록 - {{ fw_80 }}, {{ fw_433 }}
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ ports }}"
