---
- name: Restore web-db.yml
  hosts: all
  tasks:
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        - http
        - https
        - mysql

    - name: 2) 서비스 종료
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - httpd
        - mariadb

    - name: 3) 서비스 설정 삭제
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.php
        - /var/lib/mysql
    
    - name: 4) 패키지 삭제
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
          - php
          - php-pdo
          - mariadb-server
          - mariadb
          - python3-PyMySQL
          - mariadb-connection-c-config
          - mariadb-common
          - mariadb-connector-command
          - mariadb-errmsg
        state: absent
  