---
- name: 0) DB 서비스 기동 - loop 테스트
  hosts: database_prod
  gather_facts: true
  vars:
    packages:
      - mariadb-server
      - python3-PyMySQL
    service: mariadb
  tasks:
    ##########################
    # 1) 패키지 설치 - mariadb, mariadb-server, python3-PyMySQL
    # 2) 서비스 기동 - maraidb
    ###########################
    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_distribution == "CentOS"

    - name: 2) 서비스 기동
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: started
        enabled: true
