---
- name: 0) DB 서비스 기동 - loop 테스트
  hosts: all
  vars:
    packages:
      - mariadb-server
      - python3-PyMySQL
    service: mariadb
  tasks:
    ##########################
    # 1) 패키지 설치 - mariadb, mariadb-server, python3-PyMySQL
    # 2) 서비스 기동 - maraidb
    ###########################
    - name: 2) 서비스 종료
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: stopped
        enabled: false

    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: absent
      when: ansible_distribution == "CentOS"
